apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ecr-token-generator-argocd.yaml
  - argocd-ecr-helm-repo-externalsecret.yaml
  - ecr-token-generator-image-pull.yaml
  - image-pull-secret-externalsecret.yaml
  - scanning-service-gateway-application.yaml
  - scanning-service-gateway-monitor-application.yaml
  - amp-scanner-gen-application.yaml
  - amp-scanner-gen-monitor-application.yaml
  - bd-updater-application.yaml
  - bitdefender-application.yaml
  - avira-monitor-application.yaml
  - threatgrid-services-application.yaml
